package flow.subflow.AccountInfo;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.SCESession;

import flow.IProjectVariables;

/**
 * The Data class handles many types of server-side operations including data
 * collection (from a data sources such as a database, or web service), variable
 * assignments and operations (like copying variable values, performing mathematic
 * operations, and collection iteration), conditional evaluation to control callflow
 * execution based on variable values, and logging/tracing statements.
 * 
 * Items created in the getDataActions() method are executed/evaluated in order
 * and if a condional branch condition evaluates to "true" then the branch is
 * activated and the execution of data actions is halted.  If no "true" conditions
 * are encountered, then all data actions will be executed/evaluated and the 
 * application will proceed to the "Default" servlet.
 * Last generated by Orchestration Designer at: 2023-FEB-16  02:30:00 PM
 */
public class CheckSel extends com.avaya.sce.runtime.Data {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-FEB-16  02:30:00 PM
	 */
	public CheckSel() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * Returns the Next item which will forward application execution
	 * to the next form in the call flow.
	 * Last generated by Orchestration Designer at: 2023-SEP-05  01:01:20 PM
	 */
	public com.avaya.sce.runtime.Next getNext(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Next next = null;
		return next;
	}
	/**
	 * Create a list of local variables used by items in the data node.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-SEP-05  01:01:20 PM
	 */
	public java.util.Collection<VariableInfo> getLocalVariables(){
		java.util.Collection<VariableInfo> variables = new java.util.ArrayList<VariableInfo>();

		return variables;
	}
	/**
	 * Creates and conditionally executes operations that have been configured
	 * in the Callflow.  This method will build a collection of operations and
	 * have the framework execute the operations by calling evaluateActions().
	 * If the evaluation causes the framework to forward to a different servlet
	 * then execution stops.
	 * Returning true from this method means that the framework has forwarded the
	 * request to a different servlet.  Returning false means that the default
	 * Next will be invoked.
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-SEP-05  01:01:20 PM
	 */
	public boolean executeDataActions(com.avaya.sce.runtimecommon.SCESession mySession) throws Exception {
		java.util.Collection actions = null;

		actions = new java.util.ArrayList(1);
		com.avaya.sce.runtime.BooleanOperation bo1 = new com.avaya.sce.runtime.BooleanOperation(com.avaya.sce.runtime.BooleanOperation.OR);
		com.avaya.sce.runtime.Expression be1 = new com.avaya.sce.runtime.Expression("expression1", "AcctInfo:ReturnCode", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "NOMATCH", false);
		bo1.addExpression(be1);
		com.avaya.sce.runtime.Expression be2 = new com.avaya.sce.runtime.Expression("expression2", "AcctInfo:ReturnCode", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "NOINPUT", false);
		bo1.addExpression(be2);
		if(evaluateActions(actions, mySession)) {
			return true;
		}
		actions = null;

		if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition1", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL, "1", false).setDebugId(428)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-DaysBal", "daysBal").setDebugId(426));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition2", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "2", false).setDebugId(430)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("ExitVDN:EXIT_VDN_SUFFIX", "ExitVDN:ACCT_INFO_RCP_POINTS", false).setDebugId(744));
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-AcctInfoTranf", "rcpPoints").setDebugId(431));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition3", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "3", false).setDebugId(738)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("ExitVDN:EXIT_VDN_SUFFIX", "ExitVDN:ACCT_INFO_LOYALITY_POINTS", false).setDebugId(745));
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-AcctInfoTranf", "3").setDebugId(739));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition4", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "4", false).setDebugId(740)).evaluate(mySession)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.varoperations.Assign("ExitVDN:EXIT_VDN_SUFFIX", "ExitVDN:ACCT_INFO_RCI_NIGHTS", false).setDebugId(746));
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-AcctInfoTranf", "4").setDebugId(741));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition5", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "5", false).setDebugId(435)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-WS_HUSResend", "crest").setDebugId(436));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition6", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "6", false).setDebugId(751)).evaluate(mySession)) {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-ExitMenu", "languageChange").setDebugId(752));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else if(((com.avaya.sce.runtime.Condition)new com.avaya.sce.runtime.Condition("condition7", "AcctInfo:Value", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "5", false).setDebugId(755)).evaluate(mySession, bo1)) {
			actions = new java.util.ArrayList(2);
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-AcctInfoTranf", "ninm").setDebugId(756));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;

		} else {
			actions = new java.util.ArrayList(1);
			actions.add(new com.avaya.sce.runtime.Next("AccountInfo-exit").setDebugId(586));
			if(evaluateActions(actions, mySession)) {
				return true;
			}
			actions = null;
		}


		// return false if the evaluation of actions did not cause a servlet forward or redirect
		return false;
	}
	
	
	@Override
	public void requestBegin(SCESession mySession) {
		// TODO Auto-generated method stub
		super.requestBegin(mySession);

		int userSelectedLanguage = mySession
				.getVariableField(IProjectVariables.ACCT_INFO, IProjectVariables.ACCT_INFO_FIELD_VALUE).getIntValue();
		String hindiProps = getServletContext().getInitParameter("HINDI_PROPERTIES");
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Acct info | HindiProps: " + hindiProps);
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
				"Acct info | User selected: " + userSelectedLanguage);
		String engProps = getServletContext().getInitParameter("ENG-PROPERTIES_LOCATION");
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Acct info | engProps: " + engProps);

		String propLoc = mySession.getVariableField(IProjectVariables.MAIN,
				IProjectVariables.MAIN_FIELD_PROPERTY_LOCATION).getStringValue();
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "Acct info | propLoc: " + propLoc);

		if (userSelectedLanguage == 6) {
//			mySession.getVariableField(IProjectVariables.MAIN, IProjectVariables.MAIN_FIELD_PROPERTY_LOCATION)
//					.setValue(hindiProps);
			
			if (propLoc.equals(engProps)) {
				mySession.getVariableField(IProjectVariables.MAIN, 
						IProjectVariables.MAIN_FIELD_PROPERTY_LOCATION).setValue(hindiProps);	
			}else if (propLoc.equals(hindiProps)) {
				mySession.getVariableField(IProjectVariables.MAIN, 
						IProjectVariables.MAIN_FIELD_PROPERTY_LOCATION).setValue(engProps);	
			}
		}

		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
				"Property Location: " + mySession
						.getVariableField(IProjectVariables.MAIN, IProjectVariables.MAIN_FIELD_PROPERTY_LOCATION)
						.getStringValue());

	}
	
	
}
