package flow.subflow.WaitingListMod;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.apache.http.HttpResponse;
import org.apache.http.NameValuePair;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.vis.club.mahindra.api.model.MemberInformationReq;
import org.vis.club.mahindra.api.model.UpcomingWaitListBkg;
import org.vis.club.mahindra.api.model.WaitListProbability;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.google.gson.Gson;

import flow.AppConstant;
import flow.IProjectVariables;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: 2023-FEB-21  02:05:14 PM
 */
public class GetWaitListBooking extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2023-FEB-21  02:05:14 PM
	 */
	public GetWaitListBooking() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Experienve Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: 2023-FEB-21  02:05:14 PM
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {

		// TODO: Add your code here!
		getUpcomingWLBkg(mySession);
	}
	
	private void getUpcomingWLBkg(com.avaya.sce.runtimecommon.SCESession mySession) {
		BufferedReader rd = null;
		UpcomingWaitListBkg wlBkgStatus = null;
		Gson gson = new Gson();
		
		String info = "";
		String jsonResponse = "";
		try {
			String config = getServletContext().getInitParameter("Configuration");

			Properties properties = loadPropertyFile(config);
			HttpClient client = HttpClientBuilder.create().build();
			String appURL = properties.getProperty("localhost_url")
							.concat(properties.getProperty("localhost_app_name"));
			String WlURL = appURL
							.concat(properties.getProperty("waiting_list_url"));
			
			String memberID = mySession.getVariableField(IProjectVariables.MEMBER_DETAILS,
					IProjectVariables.MEMBER_DETAILS_FIELD_MEMBER_ID)
					.getStringValue();
			
			String memberShipID = mySession.getVariableField(IProjectVariables.MEMBER_DETAILS,
					IProjectVariables.MEMBER_DETAILS_FIELD_MEMBER_SHIP_ID)
					.getStringValue();			
			
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "WL Mod | memberID, memberShipID: " + memberID+", "+memberShipID);

			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "WL Mod URL: " + WlURL);

			HttpPost post = new HttpPost(WlURL);
			post.addHeader("Content-Type", "application/json");

//			List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();
//
//			nameValuePairs.add(new BasicNameValuePair(AppConstant.MEMEBER_ID, memberID));
//			nameValuePairs.add(new BasicNameValuePair(AppConstant.MEMEBERSHIP_ID, memberShipID));

//			post.setEntity(new UrlEncodedFormEntity(nameValuePairs));
//			StringEntity stringEntity = new StringEntity("{\n" + 
//					"    \"MemberID\": \""+memberID+"\"\n" + 
//					"    \"MembershipId\": \""+memberShipID+"\"\n" + 
//					"}");
//			post.setEntity(stringEntity);
			

			MemberInformationReq memberInformationReq=new MemberInformationReq();
			memberInformationReq.setMemberID(memberID);
			memberInformationReq.setMemberShipID(memberShipID);
			
			String json = gson.toJson(memberInformationReq);
			
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, "WL Mod | Upcoming Bkg json req : " + json);
			
			StringEntity stringEntity=new StringEntity(json);
			
			post.setEntity(stringEntity);
			
			HttpResponse response = client.execute(post);

			rd = new BufferedReader(new InputStreamReader(response.getEntity().getContent()));

			while ((info = rd.readLine()) != null) {
				jsonResponse += (info);
			}
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
					"WL Mod Json response " + jsonResponse);
			wlBkgStatus = gson.fromJson(jsonResponse, UpcomingWaitListBkg.class);
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO, ""+wlBkgStatus);
			
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
					"WL Mod wlBkgStatus response " + wlBkgStatus);
			
			if (wlBkgStatus!=null && wlBkgStatus.getGetWaitListProbability()!=null
					&& !wlBkgStatus.getGetWaitListProbability().isEmpty()) {
			
				mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
						"WL Mod probaability " + wlBkgStatus.getGetWaitListProbability());
				
				List<WaitListProbability> waitListProbability = wlBkgStatus.getGetWaitListProbability();

				mySession.getVariableField(IProjectVariables.WAITING_LIST_MOD,
						IProjectVariables.WAITING_LIST_MOD_FIELD_IS_BOOKING_AVAILABLE)
						.setValue(true);
			} else {
				mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
						"WL Mod API Failure " + wlBkgStatus);
				mySession.getVariableField(IProjectVariables.WAITING_LIST_MOD,
						IProjectVariables.WAITING_LIST_MOD_FIELD_IS_BOOKING_AVAILABLE)
						.setValue(false);
			}

		} catch (IOException e) {
			mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
					"WL Mod | Exception While Getting the details of WL MOD " + e);
		} finally {
			try {
				rd.close();
			} catch (IOException e) {
				mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_INFO,
						"WL Mod | Exception While Closing Buffered Reader " + e);
			}
		}
	}
	
	/**
     * @param config 
     * @return
     * @throws FileNotFoundException
     * @throws IOException
     */
	private static Properties loadPropertyFile(String config) throws FileNotFoundException, IOException {
		FileReader reader = null;
		reader = new FileReader(config);
		Properties properties = new Properties();
		properties.load(reader);
		return properties;
	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: 2023-SEP-05  01:01:25 PM
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("WaitingListMod-WaitingListBooking", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
