package hindi.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2023-FEB-21  03:12:22 PM
 */
public class std_hi_in extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(1040);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: std_a
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a", "0001.wav", ":a"); 

		// phrase: std_b
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b", "0002.wav", ":b"); 

		// phrase: std_c
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c", "0003.wav", ":c"); 

		// phrase: std_d
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d", "0004.wav", ":d"); 

		// phrase: std_e
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e", "0005.wav", ":e"); 

		// phrase: std_f
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f", "0006.wav", ":f"); 

		// phrase: std_g
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g", "0007.wav", ":g"); 

		// phrase: std_h
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h", "0008.wav", ":h"); 

		// phrase: std_i
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i", "0009.wav", ":i"); 

		// phrase: std_j
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j", "0010.wav", ":j"); 

		// phrase: std_k
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k", "0011.wav", ":k"); 

		// phrase: std_l
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l", "0012.wav", ":l"); 

		// phrase: std_m
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m", "0013.wav", ":m"); 

		// phrase: std_n
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n", "0014.wav", ":n"); 

		// phrase: std_o
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o", "0015.wav", ":o"); 

		// phrase: std_p
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p", "0016.wav", ":p"); 

		// phrase: std_q
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q", "0017.wav", ":q"); 

		// phrase: std_r
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r", "0018.wav", ":r"); 

		// phrase: std_s
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s", "0019.wav", ":s"); 

		// phrase: std_t
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t", "0020.wav", ":t"); 

		// phrase: std_u
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u", "0021.wav", ":u"); 

		// phrase: std_v
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v", "0022.wav", ":v"); 

		// phrase: std_w
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w", "0023.wav", ":w"); 

		// phrase: std_x
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x", "0024.wav", ":x"); 

		// phrase: std_y
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y", "0025.wav", ":y"); 

		// phrase: std_z
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z", "0026.wav", ":z"); 

		// phrase: std_star
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_star", "0027.wav", ":star"); 

		// phrase: std_hash
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hash", "0028.wav", ":hash"); 

		// phrase: std_minus
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus", "0029.wav", ":minus"); 

		// phrase: std_0
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0", "0030.wav", ":0"); 

		// phrase: std_1
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1", "0031.wav", ":1"); 

		// phrase: std_2
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2", "0032.wav", ":2"); 

		// phrase: std_3
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3", "0033.wav", ":3"); 

		// phrase: std_4
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4", "0034.wav", ":4"); 

		// phrase: std_5
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5", "0035.wav", ":5"); 

		// phrase: std_6
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6", "0036.wav", ":6"); 

		// phrase: std_7
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7", "0037.wav", ":7"); 

		// phrase: std_8
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8", "0038.wav", ":8"); 

		// phrase: std_9
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9", "0039.wav", ":9"); 

		// phrase: std_10
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10", "0040.wav", ":10"); 

		// phrase: std_11
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11", "0041.wav", ":11"); 

		// phrase: std_12
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12", "0042.wav", ":12"); 

		// phrase: std_13
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13", "0043.wav", ":13"); 

		// phrase: std_14
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14", "0044.wav", ":14"); 

		// phrase: std_15
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15", "0045.wav", ":15"); 

		// phrase: std_16
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16", "0046.wav", ":16"); 

		// phrase: std_17
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17", "0047.wav", ":17"); 

		// phrase: std_18
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18", "0048.wav", ":18"); 

		// phrase: std_19
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19", "0049.wav", ":19"); 

		// phrase: std_20
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20", "0050.wav", ":20"); 

		// phrase: std_21
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_21", "0051.wav", ":21"); 

		// phrase: std_22
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_22", "0052.wav", ":22"); 

		// phrase: std_23
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_23", "0053.wav", ":23"); 

		// phrase: std_24
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_24", "0054.wav", ":24"); 

		// phrase: std_25
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_25", "0055.wav", ":25"); 

		// phrase: std_26
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_26", "0056.wav", ":26"); 

		// phrase: std_27
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_27", "0057.wav", ":27"); 

		// phrase: std_28
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_28", "0058.wav", ":28"); 

		// phrase: std_29
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_29", "0059.wav", ":29"); 

		// phrase: std_30
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30", "0060.wav", ":30"); 

		// phrase: std_31
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_31", "0061.wav", ":31"); 

		// phrase: std_32
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_32", "0062.wav", ":32"); 

		// phrase: std_33
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_33", "0063.wav", ":33"); 

		// phrase: std_34
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_34", "0064.wav", ":34"); 

		// phrase: std_35
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_35", "0065.wav", ":35"); 

		// phrase: std_36
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_36", "0066.wav", ":36"); 

		// phrase: std_37
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_37", "0067.wav", ":37"); 

		// phrase: std_38
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_38", "0068.wav", ":38"); 

		// phrase: std_39
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_39", "0069.wav", ":39"); 

		// phrase: std_40
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40", "0070.wav", ":40"); 

		// phrase: std_41
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_41", "0071.wav", ":41"); 

		// phrase: std_42
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_42", "0072.wav", ":42"); 

		// phrase: std_43
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_43", "0073.wav", ":43"); 

		// phrase: std_44
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_44", "0074.wav", ":44"); 

		// phrase: std_45
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_45", "0075.wav", ":45"); 

		// phrase: std_46
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_46", "0076.wav", ":46"); 

		// phrase: std_47
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_47", "0077.wav", ":47"); 

		// phrase: std_48
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_48", "0078.wav", ":48"); 

		// phrase: std_49
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_49", "0079.wav", ":49"); 

		// phrase: std_50
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50", "0080.wav", ":50"); 

		// phrase: std_51
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_51", "0081.wav", ":51"); 

		// phrase: std_52
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_52", "0082.wav", ":52"); 

		// phrase: std_53
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_53", "0083.wav", ":53"); 

		// phrase: std_54
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_54", "0084.wav", ":54"); 

		// phrase: std_55
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_55", "0085.wav", ":55"); 

		// phrase: std_56
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_56", "0086.wav", ":56"); 

		// phrase: std_57
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_57", "0087.wav", ":57"); 

		// phrase: std_58
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_58", "0088.wav", ":58"); 

		// phrase: std_59
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_59", "0089.wav", ":59"); 

		// phrase: std_60
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60", "0090.wav", ":60"); 

		// phrase: std_61
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_61", "0091.wav", ":61"); 

		// phrase: std_62
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_62", "0092.wav", ":62"); 

		// phrase: std_63
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_63", "0093.wav", ":63"); 

		// phrase: std_64
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_64", "0094.wav", ":64"); 

		// phrase: std_65
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_65", "0095.wav", ":65"); 

		// phrase: std_66
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_66", "0096.wav", ":66"); 

		// phrase: std_67
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_67", "0097.wav", ":67"); 

		// phrase: std_68
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_68", "0098.wav", ":68"); 

		// phrase: std_69
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_69", "0099.wav", ":69"); 

		// phrase: std_70
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70", "0100.wav", ":70"); 

		// phrase: std_71
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_71", "0101.wav", ":71"); 

		// phrase: std_72
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_72", "0102.wav", ":72"); 

		// phrase: std_73
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_73", "0103.wav", ":73"); 

		// phrase: std_74
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_74", "0104.wav", ":74"); 

		// phrase: std_75
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_75", "0105.wav", ":75"); 

		// phrase: std_76
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_76", "0106.wav", ":76"); 

		// phrase: std_77
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_77", "0107.wav", ":77"); 

		// phrase: std_78
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_78", "0108.wav", ":78"); 

		// phrase: std_79
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_79", "0109.wav", ":79"); 

		// phrase: std_80
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80", "0110.wav", ":80"); 

		// phrase: std_81
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_81", "0111.wav", ":81"); 

		// phrase: std_82
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_82", "0112.wav", ":82"); 

		// phrase: std_83
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_83", "0113.wav", ":83"); 

		// phrase: std_84
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_84", "0114.wav", ":84"); 

		// phrase: std_85
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_85", "0115.wav", ":85"); 

		// phrase: std_86
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_86", "0116.wav", ":86"); 

		// phrase: std_87
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_87", "0117.wav", ":87"); 

		// phrase: std_88
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_88", "0118.wav", ":88"); 

		// phrase: std_89
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_89", "0119.wav", ":89"); 

		// phrase: std_90
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90", "0120.wav", ":90"); 

		// phrase: std_91
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_91", "0121.wav", ":91"); 

		// phrase: std_92
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_92", "0122.wav", ":92"); 

		// phrase: std_93
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_93", "0123.wav", ":93"); 

		// phrase: std_94
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_94", "0124.wav", ":94"); 

		// phrase: std_95
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_95", "0125.wav", ":95"); 

		// phrase: std_96
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_96", "0126.wav", ":96"); 

		// phrase: std_97
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_97", "0127.wav", ":97"); 

		// phrase: std_98
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_98", "0128.wav", ":98"); 

		// phrase: std_99
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_99", "0129.wav", ":99"); 

		// phrase: std_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100", "0130.wav", ":100"); 

		// phrase: std_1000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000", "0131.wav", ":1000"); 

		// phrase: std_100000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000", "0132.wav", ":100000"); 

		// phrase: std_10000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000", "0133.wav", ":10000000"); 

		// phrase: std_1000000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000", "0134.wav", ":1000000000"); 

		// phrase: std_100000000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000000000", "0135.wav", ":100000000000"); 

		// phrase: std_10000000000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000000000", "0136.wav", ":10000000000000"); 

		// phrase: std_1000000000000000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000000000", "0137.wav", ":1000000000000000"); 

		// phrase: std_a_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a_falling", "0140.wav", ":a."); 

		// phrase: std_b_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b_falling", "0141.wav", ":b."); 

		// phrase: std_c_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c_falling", "0142.wav", ":c."); 

		// phrase: std_d_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d_falling", "0143.wav", ":d."); 

		// phrase: std_e_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_falling", "0144.wav", ":e."); 

		// phrase: std_f_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f_falling", "0145.wav", ":f."); 

		// phrase: std_g_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g_falling", "0146.wav", ":g."); 

		// phrase: std_h_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h_falling", "0147.wav", ":h."); 

		// phrase: std_i_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i_falling", "0148.wav", ":i."); 

		// phrase: std_j_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j_falling", "0149.wav", ":j."); 

		// phrase: std_k_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k_falling", "0150.wav", ":k."); 

		// phrase: std_l_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l_falling", "0151.wav", ":l."); 

		// phrase: std_m_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m_falling", "0152.wav", ":m."); 

		// phrase: std_n_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n_falling", "0153.wav", ":n."); 

		// phrase: std_o_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o_falling", "0154.wav", ":o."); 

		// phrase: std_p_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p_falling", "0155.wav", ":p."); 

		// phrase: std_q_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q_falling", "0156.wav", ":q."); 

		// phrase: std_r_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r_falling", "0157.wav", ":r."); 

		// phrase: std_s_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s_falling", "0158.wav", ":s."); 

		// phrase: std_t_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t_falling", "0159.wav", ":t."); 

		// phrase: std_u_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u_falling", "0160.wav", ":u."); 

		// phrase: std_v_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v_falling", "0161.wav", ":v."); 

		// phrase: std_w_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w_falling", "0162.wav", ":w."); 

		// phrase: std_x_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x_falling", "0163.wav", ":x."); 

		// phrase: std_y_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y_falling", "0164.wav", ":y."); 

		// phrase: std_z_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z_falling", "0165.wav", ":z."); 

		// phrase: std_star_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_star_falling", "0166.wav", ":star."); 

		// phrase: std_hash_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hash_falling", "0167.wav", ":hash."); 

		// phrase: std_minus_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus_falling", "0168.wav", ":minus."); 

		// phrase: std_0_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0_falling", "0169.wav", ":0."); 

		// phrase: std_1_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_falling", "0170.wav", ":1."); 

		// phrase: std_2_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_falling", "0171.wav", ":2."); 

		// phrase: std_3_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3_falling", "0172.wav", ":3."); 

		// phrase: std_4_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4_falling", "0173.wav", ":4."); 

		// phrase: std_5_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5_falling", "0174.wav", ":5."); 

		// phrase: std_6_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6_falling", "0175.wav", ":6."); 

		// phrase: std_7_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7_falling", "0176.wav", ":7."); 

		// phrase: std_8_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8_falling", "0177.wav", ":8."); 

		// phrase: std_9_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9_falling", "0178.wav", ":9."); 

		// phrase: std_10_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10_falling", "0179.wav", ":10."); 

		// phrase: std_11_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11_falling", "0180.wav", ":11."); 

		// phrase: std_12_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12_falling", "0181.wav", ":12."); 

		// phrase: std_13_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13_falling", "0182.wav", ":13."); 

		// phrase: std_14_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14_falling", "0183.wav", ":14."); 

		// phrase: std_15_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15_falling", "0184.wav", ":15."); 

		// phrase: std_16_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16_falling", "0185.wav", ":16."); 

		// phrase: std_17_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17_falling", "0186.wav", ":17."); 

		// phrase: std_18_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18_falling", "0187.wav", ":18."); 

		// phrase: std_19_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19_falling", "0188.wav", ":19."); 

		// phrase: std_20_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20_falling", "0189.wav", ":20."); 

		// phrase: std_21_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_21_falling", "0190.wav", ":21."); 

		// phrase: std_22_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_22_falling", "0191.wav", ":22."); 

		// phrase: std_23_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_23_falling", "0192.wav", ":23."); 

		// phrase: std_24_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_24_falling", "0193.wav", ":24."); 

		// phrase: std_25_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_25_falling", "0194.wav", ":25."); 

		// phrase: std_26_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_26_falling", "0195.wav", ":26."); 

		// phrase: std_27_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_27_falling", "0196.wav", ":27."); 

		// phrase: std_28_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_28_falling", "0197.wav", ":28."); 

		// phrase: std_29_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_29_falling", "0198.wav", ":29."); 

		// phrase: std_30_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30_falling", "0199.wav", ":30."); 

		// phrase: std_31_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_31_falling", "0200.wav", ":31."); 

		// phrase: std_32_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_32_falling", "0201.wav", ":32."); 

		// phrase: std_33_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_33_falling", "0202.wav", ":33."); 

		// phrase: std_34_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_34_falling", "0203.wav", ":34."); 

		// phrase: std_35_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_35_falling", "0204.wav", ":35."); 

		// phrase: std_36_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_36_falling", "0205.wav", ":36."); 

		// phrase: std_37_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_37_falling", "0206.wav", ":37."); 

		// phrase: std_38_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_38_falling", "0207.wav", ":38."); 

		// phrase: std_39_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_39_falling", "0208.wav", ":39."); 

		// phrase: std_40_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40_falling", "0209.wav", ":40."); 

		// phrase: std_41_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_41_falling", "0210.wav", ":41."); 

		// phrase: std_42_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_42_falling", "0211.wav", ":42."); 

		// phrase: std_43_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_43_falling", "0212.wav", ":43."); 

		// phrase: std_44_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_44_falling", "0213.wav", ":44."); 

		// phrase: std_45_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_45_falling", "0214.wav", ":45."); 

		// phrase: std_46_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_46_falling", "0215.wav", ":46."); 

		// phrase: std_47_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_47_falling", "0216.wav", ":47."); 

		// phrase: std_48_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_48_falling", "0217.wav", ":48."); 

		// phrase: std_49_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_49_falling", "0218.wav", ":49."); 

		// phrase: std_50_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50_falling", "0219.wav", ":50."); 

		// phrase: std_51_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_51_falling", "0220.wav", ":51."); 

		// phrase: std_52_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_52_falling", "0221.wav", ":52."); 

		// phrase: std_53_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_53_falling", "0222.wav", ":53."); 

		// phrase: std_54_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_54_falling", "0223.wav", ":54."); 

		// phrase: std_55_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_55_falling", "0224.wav", ":55."); 

		// phrase: std_56_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_56_falling", "0225.wav", ":56."); 

		// phrase: std_57_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_57_falling", "0226.wav", ":57."); 

		// phrase: std_58_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_58_falling", "0227.wav", ":58."); 

		// phrase: std_59_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_59_falling", "0228.wav", ":59."); 

		// phrase: std_60_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60_falling", "0229.wav", ":60."); 

		// phrase: std_61_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_61_falling", "0230.wav", ":61."); 

		// phrase: std_62_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_62_falling", "0231.wav", ":62."); 

		// phrase: std_63_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_63_falling", "0232.wav", ":63."); 

		// phrase: std_64_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_64_falling", "0233.wav", ":64."); 

		// phrase: std_65_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_65_falling", "0234.wav", ":65."); 

		// phrase: std_66_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_66_falling", "0235.wav", ":66."); 

		// phrase: std_67_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_67_falling", "0236.wav", ":67."); 

		// phrase: std_68_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_68_falling", "0237.wav", ":68."); 

		// phrase: std_69_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_69_falling", "0238.wav", ":69."); 

		// phrase: std_70_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70_falling", "0239.wav", ":70."); 

		// phrase: std_71_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_71_falling", "0240.wav", ":71."); 

		// phrase: std_72_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_72_falling", "0241.wav", ":72."); 

		// phrase: std_73_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_73_falling", "0242.wav", ":73."); 

		// phrase: std_74_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_74_falling", "0243.wav", ":74."); 

		// phrase: std_75_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_75_falling", "0244.wav", ":75."); 

		// phrase: std_76_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_76_falling", "0245.wav", ":76."); 

		// phrase: std_77_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_77_falling", "0246.wav", ":77."); 

		// phrase: std_78_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_78_falling", "0247.wav", ":78."); 

		// phrase: std_79_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_79_falling", "0248.wav", ":79."); 

		// phrase: std_80_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80_falling", "0249.wav", ":80."); 

		// phrase: std_81_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_81_falling", "0250.wav", ":81."); 

		// phrase: std_82_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_82_falling", "0251.wav", ":82."); 

		// phrase: std_83_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_83_falling", "0252.wav", ":83."); 

		// phrase: std_84_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_84_falling", "0253.wav", ":84."); 

		// phrase: std_85_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_85_falling", "0254.wav", ":85."); 

		// phrase: std_86_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_86_falling", "0255.wav", ":86."); 

		// phrase: std_87_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_87_falling", "0256.wav", ":87."); 

		// phrase: std_88_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_88_falling", "0257.wav", ":88."); 

		// phrase: std_89_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_89_falling", "0258.wav", ":89."); 

		// phrase: std_90_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90_falling", "0259.wav", ":90."); 

		// phrase: std_91_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_91_falling", "0260.wav", ":91."); 

		// phrase: std_92_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_92_falling", "0261.wav", ":92."); 

		// phrase: std_93_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_93_falling", "0262.wav", ":93."); 

		// phrase: std_94_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_94_falling", "0263.wav", ":94."); 

		// phrase: std_95_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_95_falling", "0264.wav", ":95."); 

		// phrase: std_96_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_96_falling", "0265.wav", ":96."); 

		// phrase: std_97_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_97_falling", "0266.wav", ":97."); 

		// phrase: std_98_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_98_falling", "0267.wav", ":98."); 

		// phrase: std_99_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_99_falling", "0268.wav", ":99."); 

		// phrase: std_100_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100_falling", "0269.wav", ":100."); 

		// phrase: std_1000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000_falling", "0270.wav", ":1000."); 

		// phrase: std_100000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000_falling", "0271.wav", ":100000."); 

		// phrase: std_10000000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000_falling", "0272.wav", ":10000000."); 

		// phrase: std_1000000000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000_falling", "0273.wav", ":1000000000."); 

		// phrase: std_100000000000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000000000_falling", "0274.wav", ":100000000000."); 

		// phrase: std_10000000000000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000000000_falling", "0275.wav", ":10000000000000."); 

		// phrase: std_1000000000000000_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000000000_falling", "0276.wav", ":1000000000000000."); 

		// phrase: std_a_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_a_raising", "0280.wav", ":a?"); 

		// phrase: std_b_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_b_raising", "0281.wav", ":b?"); 

		// phrase: std_c_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_c_raising", "0282.wav", ":c?"); 

		// phrase: std_d_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_d_raising", "0283.wav", ":d?"); 

		// phrase: std_e_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_e_raising", "0284.wav", ":e?"); 

		// phrase: std_f_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_f_raising", "0285.wav", ":f?"); 

		// phrase: std_g_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_g_raising", "0286.wav", ":g?"); 

		// phrase: std_h_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_h_raising", "0287.wav", ":h?"); 

		// phrase: std_i_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_i_raising", "0288.wav", ":i?"); 

		// phrase: std_j_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_j_raising", "0289.wav", ":j?"); 

		// phrase: std_k_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_k_raising", "0290.wav", ":k?"); 

		// phrase: std_l_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_l_raising", "0291.wav", ":l?"); 

		// phrase: std_m_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_m_raising", "0292.wav", ":m?"); 

		// phrase: std_n_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_n_raising", "0293.wav", ":n?"); 

		// phrase: std_o_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_o_raising", "0294.wav", ":o?"); 

		// phrase: std_p_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_p_raising", "0295.wav", ":p?"); 

		// phrase: std_q_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_q_raising", "0296.wav", ":q?"); 

		// phrase: std_r_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_r_raising", "0297.wav", ":r?"); 

		// phrase: std_s_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_s_raising", "0298.wav", ":s?"); 

		// phrase: std_t_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_t_raising", "0299.wav", ":t?"); 

		// phrase: std_u_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_u_raising", "0300.wav", ":u?"); 

		// phrase: std_v_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_v_raising", "0301.wav", ":v?"); 

		// phrase: std_w_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_w_raising", "0302.wav", ":w?"); 

		// phrase: std_x_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_x_raising", "0303.wav", ":x?"); 

		// phrase: std_y_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_y_raising", "0304.wav", ":y?"); 

		// phrase: std_z_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_z_raising", "0305.wav", ":z?"); 

		// phrase: std_star_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_star_raising", "0306.wav", ":star?"); 

		// phrase: std_hash_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_hash_raising", "0307.wav", ":hash?"); 

		// phrase: std_minus_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus_raising", "0308.wav", ":minus?"); 

		// phrase: std_0_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_0_raising", "0309.wav", ":0?"); 

		// phrase: std_1_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1_raising", "0310.wav", ":1?"); 

		// phrase: std_2_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_2_raising", "0311.wav", ":2?"); 

		// phrase: std_3_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_3_raising", "0312.wav", ":3?"); 

		// phrase: std_4_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_4_raising", "0313.wav", ":4?"); 

		// phrase: std_5_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_5_raising", "0314.wav", ":5?"); 

		// phrase: std_6_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_6_raising", "0315.wav", ":6?"); 

		// phrase: std_7_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_7_raising", "0316.wav", ":7?"); 

		// phrase: std_8_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_8_raising", "0317.wav", ":8?"); 

		// phrase: std_9_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_9_raising", "0318.wav", ":9?"); 

		// phrase: std_10_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10_raising", "0319.wav", ":10?"); 

		// phrase: std_11_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_11_raising", "0320.wav", ":11?"); 

		// phrase: std_12_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_12_raising", "0321.wav", ":12?"); 

		// phrase: std_13_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_13_raising", "0322.wav", ":13?"); 

		// phrase: std_14_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_14_raising", "0323.wav", ":14?"); 

		// phrase: std_15_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_15_raising", "0324.wav", ":15?"); 

		// phrase: std_16_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_16_raising", "0325.wav", ":16?"); 

		// phrase: std_17_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_17_raising", "0326.wav", ":17?"); 

		// phrase: std_18_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_18_raising", "0327.wav", ":18?"); 

		// phrase: std_19_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_19_raising", "0328.wav", ":19?"); 

		// phrase: std_20_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_20_raising", "0329.wav", ":20?"); 

		// phrase: std_21_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_21_raising", "0330.wav", ":21?"); 

		// phrase: std_22_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_22_raising", "0331.wav", ":22?"); 

		// phrase: std_23_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_23_raising", "0332.wav", ":23?"); 

		// phrase: std_24_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_24_raising", "0333.wav", ":24?"); 

		// phrase: std_25_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_25_raising", "0334.wav", ":25?"); 

		// phrase: std_26_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_26_raising", "0335.wav", ":26?"); 

		// phrase: std_27_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_27_raising", "0336.wav", ":27?"); 

		// phrase: std_28_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_28_raising", "0337.wav", ":28?"); 

		// phrase: std_29_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_29_raising", "0338.wav", ":29?"); 

		// phrase: std_30_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_30_raising", "0339.wav", ":30?"); 

		// phrase: std_31_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_31_raising", "0340.wav", ":31?"); 

		// phrase: std_32_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_32_raising", "0341.wav", ":32?"); 

		// phrase: std_33_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_33_raising", "0342.wav", ":33?"); 

		// phrase: std_34_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_34_raising", "0343.wav", ":34?"); 

		// phrase: std_35_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_35_raising", "0344.wav", ":35?"); 

		// phrase: std_36_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_36_raising", "0345.wav", ":36?"); 

		// phrase: std_37_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_37_raising", "0346.wav", ":37?"); 

		// phrase: std_38_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_38_raising", "0347.wav", ":38?"); 

		// phrase: std_39_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_39_raising", "0348.wav", ":39?"); 

		// phrase: std_40_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_40_raising", "0349.wav", ":40?"); 

		// phrase: std_41_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_41_raising", "0350.wav", ":41?"); 

		// phrase: std_42_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_42_raising", "0351.wav", ":42?"); 

		// phrase: std_43_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_43_raising", "0352.wav", ":43?"); 

		// phrase: std_44_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_44_raising", "0353.wav", ":44?"); 

		// phrase: std_45_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_45_raising", "0354.wav", ":45?"); 

		// phrase: std_46_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_46_raising", "0355.wav", ":46?"); 

		// phrase: std_47_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_47_raising", "0356.wav", ":47?"); 

		// phrase: std_48_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_48_raising", "0357.wav", ":48?"); 

		// phrase: std_49_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_49_raising", "0358.wav", ":49?"); 

		// phrase: std_50_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_50_raising", "0359.wav", ":50?"); 

		// phrase: std_51_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_51_raising", "0360.wav", ":51?"); 

		// phrase: std_52_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_52_raising", "0361.wav", ":52?"); 

		// phrase: std_53_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_53_raising", "0362.wav", ":53?"); 

		// phrase: std_54_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_54_raising", "0363.wav", ":54?"); 

		// phrase: std_55_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_55_raising", "0364.wav", ":55?"); 

		// phrase: std_56_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_56_raising", "0365.wav", ":56?"); 

		// phrase: std_57_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_57_raising", "0366.wav", ":57?"); 

		// phrase: std_58_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_58_raising", "0367.wav", ":58?"); 

		// phrase: std_59_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_59_raising", "0368.wav", ":59?"); 

		// phrase: std_60_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_60_raising", "0369.wav", ":60?"); 

		// phrase: std_61_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_61_raising", "0370.wav", ":61?"); 

		// phrase: std_62_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_62_raising", "0371.wav", ":62?"); 

		// phrase: std_63_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_63_raising", "0372.wav", ":63?"); 

		// phrase: std_64_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_64_raising", "0373.wav", ":64?"); 

		// phrase: std_65_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_65_raising", "0374.wav", ":65?"); 

		// phrase: std_66_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_66_raising", "0375.wav", ":66?"); 

		// phrase: std_67_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_67_raising", "0376.wav", ":67?"); 

		// phrase: std_68_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_68_raising", "0377.wav", ":68?"); 

		// phrase: std_69_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_69_raising", "0378.wav", ":69?"); 

		// phrase: std_70_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_70_raising", "0379.wav", ":70?"); 

		// phrase: std_71_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_71_raising", "0380.wav", ":71?"); 

		// phrase: std_72_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_72_raising", "0381.wav", ":72?"); 

		// phrase: std_73_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_73_raising", "0382.wav", ":73?"); 

		// phrase: std_74_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_74_raising", "0383.wav", ":74?"); 

		// phrase: std_75_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_75_raising", "0384.wav", ":75?"); 

		// phrase: std_76_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_76_raising", "0385.wav", ":76?"); 

		// phrase: std_77_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_77_raising", "0386.wav", ":77?"); 

		// phrase: std_78_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_78_raising", "0387.wav", ":78?"); 

		// phrase: std_79_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_79_raising", "0388.wav", ":79?"); 

		// phrase: std_80_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_80_raising", "0389.wav", ":80?"); 

		// phrase: std_81_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_81_raising", "0390.wav", ":81?"); 

		// phrase: std_82_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_82_raising", "0391.wav", ":82?"); 

		// phrase: std_83_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_83_raising", "0392.wav", ":83?"); 

		// phrase: std_84_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_84_raising", "0393.wav", ":84?"); 

		// phrase: std_85_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_85_raising", "0394.wav", ":85?"); 

		// phrase: std_86_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_86_raising", "0395.wav", ":86?"); 

		// phrase: std_87_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_87_raising", "0396.wav", ":87?"); 

		// phrase: std_88_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_88_raising", "0397.wav", ":88?"); 

		// phrase: std_89_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_89_raising", "0398.wav", ":89?"); 

		// phrase: std_90_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_90_raising", "0399.wav", ":90?"); 

		// phrase: std_91_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_91_raising", "0400.wav", ":91?"); 

		// phrase: std_92_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_92_raising", "0401.wav", ":92?"); 

		// phrase: std_93_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_93_raising", "0402.wav", ":93?"); 

		// phrase: std_94_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_94_raising", "0403.wav", ":94?"); 

		// phrase: std_95_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_95_raising", "0404.wav", ":95?"); 

		// phrase: std_96_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_96_raising", "0405.wav", ":96?"); 

		// phrase: std_97_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_97_raising", "0406.wav", ":97?"); 

		// phrase: std_98_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_98_raising", "0407.wav", ":98?"); 

		// phrase: std_99_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_99_raising", "0408.wav", ":99?"); 

		// phrase: std_100_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100_raising", "0409.wav", ":100?"); 

		// phrase: std_1000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000_raising", "0410.wav", ":1000?"); 

		// phrase: std_100000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000_raising", "0411.wav", ":100000?"); 

		// phrase: std_10000000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000_raising", "0412.wav", ":10000000?"); 

		// phrase: std_1000000000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000_raising", "0413.wav", ":1000000000?"); 

		// phrase: std_100000000000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_100000000000_raising", "0414.wav", ":100000000000?"); 

		// phrase: std_10000000000000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_10000000000000_raising", "0415.wav", ":10000000000000?"); 

		// phrase: std_1000000000000000_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_1000000000000000_raising", "0416.wav", ":1000000000000000?"); 

		// phrase: std_january
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_january", "0425.wav", "january"); 

		// phrase: std_february
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_february", "0426.wav", "february"); 

		// phrase: std_march
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_march", "0427.wav", "march"); 

		// phrase: std_april
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_april", "0428.wav", "april"); 

		// phrase: std_may
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_may", "0429.wav", "may"); 

		// phrase: std_june
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_june", "0430.wav", "june"); 

		// phrase: std_july
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_july", "0431.wav", "july"); 

		// phrase: std_august
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_august", "0432.wav", "august"); 

		// phrase: std_september
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_september", "0433.wav", "september"); 

		// phrase: std_october
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_october", "0434.wav", "october"); 

		// phrase: std_november
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_november", "0435.wav", "november"); 

		// phrase: std_december
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_december", "0436.wav", "december"); 

		// phrase: std_sunday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sunday", "0440.wav", "sunday"); 

		// phrase: std_monday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_monday", "0441.wav", "monday"); 

		// phrase: std_tuesday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_tuesday", "0442.wav", "tuesday"); 

		// phrase: std_wednesday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_wednesday", "0443.wav", "wednesday"); 

		// phrase: std_thursday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_thursday", "0444.wav", "thursday"); 

		// phrase: std_friday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_friday", "0445.wav", "friday"); 

		// phrase: std_saturday
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_saturday", "0446.wav", "saturday"); 

		// phrase: std_january_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_january_falling", "0460.wav", "january."); 

		// phrase: std_february_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_february_falling", "0461.wav", "february."); 

		// phrase: std_march_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_march_falling", "0462.wav", "march."); 

		// phrase: std_april_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_april_falling", "0463.wav", "april."); 

		// phrase: std_may_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_may_falling", "0464.wav", "may."); 

		// phrase: std_june_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_june_falling", "0465.wav", "june."); 

		// phrase: std_july_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_july_falling", "0466.wav", "july."); 

		// phrase: std_august_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_august_falling", "0467.wav", "august."); 

		// phrase: std_september_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_september_falling", "0468.wav", "september."); 

		// phrase: std_october_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_october_falling", "0469.wav", "october."); 

		// phrase: std_november_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_november_falling", "0470.wav", "november."); 

		// phrase: std_december_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_december_falling", "0471.wav", "december."); 

		// phrase: std_sunday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sunday_falling", "0480.wav", "sunday."); 

		// phrase: std_monday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_monday_falling", "0481.wav", "monday."); 

		// phrase: std_tuesday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_tuesday_falling", "0482.wav", "tuesday."); 

		// phrase: std_wednesday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_wednesday_falling", "0483.wav", "wednesday."); 

		// phrase: std_thursday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_thursday_falling", "0484.wav", "thursday."); 

		// phrase: std_friday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_friday_falling", "0485.wav", "friday."); 

		// phrase: std_saturday_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_saturday_falling", "0486.wav", "saturday."); 

		// phrase: std_january_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_january_raising", "0500.wav", "january?"); 

		// phrase: std_february_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_february_raising", "0501.wav", "february?"); 

		// phrase: std_march_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_march_raising", "0502.wav", "march?"); 

		// phrase: std_april_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_april_raising", "0503.wav", "april?"); 

		// phrase: std_may_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_may_raising", "0504.wav", "may?"); 

		// phrase: std_june_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_june_raising", "0505.wav", "june?"); 

		// phrase: std_july_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_july_raising", "0506.wav", "july?"); 

		// phrase: std_august_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_august_raising", "0507.wav", "august?"); 

		// phrase: std_september_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_september_raising", "0508.wav", "september?"); 

		// phrase: std_october_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_october_raising", "0509.wav", "october?"); 

		// phrase: std_november_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_november_raising", "0510.wav", "november?"); 

		// phrase: std_december_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_december_raising", "0511.wav", "december?"); 

		// phrase: std_sunday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sunday_raising", "0520.wav", "sunday?"); 

		// phrase: std_monday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_monday_raising", "0521.wav", "monday?"); 

		// phrase: std_tuesday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_tuesday_raising", "0522.wav", "tuesday?"); 

		// phrase: std_wednesday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_wednesday_raising", "0523.wav", "wednesday?"); 

		// phrase: std_thursday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_thursday_raising", "0524.wav", "thursday?"); 

		// phrase: std_friday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_friday_raising", "0525.wav", "friday?"); 

		// phrase: std_saturday_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_saturday_raising", "0526.wav", "saturday?"); 

		// phrase: std_baje
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_baje", "1000.wav", "baje"); 

		// phrase: std_bajkar
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_bajkar", "1001.wav", "bajkar"); 

		// phrase: std_din
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_din", "1002.wav", "din"); 

		// phrase: std_raatri
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_raatri", "1003.wav", "raatri"); 

		// phrase: std_subah
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_subah", "1004.wav", "subah"); 

		// phrase: std_point
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_point", "1005.wav", "point"); 

		// phrase: std_point_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_point_falling", "1006.wav", "point."); 

		// phrase: std_point_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_point_raising", "1007.wav", "point?"); 

		// phrase: std_shaam
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_shaam", "1008.wav", "shaam"); 

		// phrase: std_dopahar
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dopahar", "1009.wav", "dopahar"); 

		// phrase: std_minute
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minute", "1010.wav", "minute"); 

		// phrase: std_and
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_and", "1011.wav", "and"); 

		// phrase: std_and_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_and_falling", "1012.wav", "and."); 

		// phrase: std_and_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_and_raising", "1013.wav", "and?"); 

		// phrase: std_cent
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cent", "1014.wav", "cent"); 

		// phrase: std_cent_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cent_falling", "1015.wav", "cent."); 

		// phrase: std_cent_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cent_raising", "1016.wav", "cent?"); 

		// phrase: std_cents
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cents", "1017.wav", "cents"); 

		// phrase: std_cents_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cents_falling", "1018.wav", "cents."); 

		// phrase: std_cents_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_cents_raising", "1019.wav", "cents?"); 

		// phrase: std_dollar
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollar", "1020.wav", "dollar"); 

		// phrase: std_dollar_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollar_falling", "1021.wav", "dollar."); 

		// phrase: std_dollar_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollar_raising", "1022.wav", "dollar?"); 

		// phrase: std_dollars
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollars", "1023.wav", "dollars"); 

		// phrase: std_paisa
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paisa", "1024.wav", "paisa"); 

		// phrase: std_paisa_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paisa_falling", "1025.wav", "paisa."); 

		// phrase: std_dollars_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollars_falling", "1026.wav", "dollars."); 

		// phrase: std_paise
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paise", "1027.wav", "paise"); 

		// phrase: std_paise_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paise_falling", "1028.wav", "paise."); 

		// phrase: std_rupee_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupee_raising", "1029.wav", "rupee?"); 

		// phrase: std_rupee
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupee", "1030.wav", "rupee"); 

		// phrase: std_rupee_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupee_falling", "1031.wav", "rupee."); 

		// phrase: std_rupees_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupees_raising", "1032.wav", "rupees?"); 

		// phrase: std_rupees
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupees", "1033.wav", "rupees"); 

		// phrase: std_rupees_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_rupees_falling", "1034.wav", "rupees."); 

		// phrase: std_dollars_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_dollars_raising", "1035.wav", "dollars?"); 

		// phrase: std_minus_hi
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus_hi", "1036.wav", "minus_hi"); 

		// phrase: std_minus_hi_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus_hi_falling", "1037.wav", "minus_hi."); 

		// phrase: std_minus_hi_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_minus_hi_raising", "1038.wav", "minus_hi?"); 

		// phrase: std_paisa_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paisa_raising", "1039.wav", "paisa?"); 

		// phrase: std_paise_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_paise_raising", "1040.wav", "paise?"); 

		// phrase: std_yes
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_yes", "1041.wav", "yes"); 

		// phrase: std_yes_raising
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_yes_raising", "1042.wav", "yes?"); 

		// phrase: std_yes_falling
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_yes_falling", "1043.wav", "yes."); 

		// phrase: std_beep
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_beep", "1044.wav", "beep"); 

		// phrase: std_sil_050
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_050", "1130.wav", "sil_050"); 

		// phrase: std_sil_100
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_100", "1131.wav", "sil_100"); 

		// phrase: std_sil_200
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_200", "1132.wav", "sil_200"); 

		// phrase: std_sil_300
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_300", "1133.wav", "sil_300"); 

		// phrase: std_sil_400
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_400", "1134.wav", "sil_400"); 

		// phrase: std_sil_500
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_500", "1135.wav", "sil_500"); 

		// phrase: std_sil_600
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "std_sil_600", "1136.wav", "sil_600"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2023-SEP-05  01:01:26 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(std_hi_in.PHRASE_MAP, phraseName));
	}
}
